In [57]:
import torch
from torch import nn

x = torch.tensor([1.])
print(x)
model = nn.Linear(1,1)
#print(model.weight)
#print(model.bias)
print(model(x))
y = x @ model.weight + model.bias # perceptron why? entropy
print(y)

tensor([1.])
tensor([-0.2897], grad_fn=<AddBackward0>)
tensor([-0.2897], grad_fn=<AddBackward0>)


In [117]:
fc1 = nn.Linear(1,100)
fc2 = nn.Linear(100,1)

x = torch.tensor([1.])
print(fc2(fc1(x)))

y = (x @ fc1.weight.T + fc1.bias) @ fc2.weight.T + fc2.bias
print(y)

model = nn.Sequential(nn.Linear(1,100), 
                      nn.Linear(100,1))
print(model(x))


class my_model(nn.Module):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        self.my_layer = nn.Sequential(nn.Linear(1,100), 
                                      nn.Linear(100,1))
    
    def forward(self, x):
        x = self.my_layer(x)
        return x

model = my_model()
x = torch.tensor([1.])
y = model(x)
print(y)

"""
# 01 
"""



tensor([0.2387], grad_fn=<AddBackward0>)
tensor([0.2387], grad_fn=<AddBackward0>)
tensor([-0.7397], grad_fn=<AddBackward0>)
tensor([-0.7069], grad_fn=<AddBackward0>)


In [198]:
import pandas as pd
import numpy as np
import torch
from torch import nn
from torch import optim
import torch.nn.functional as func
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression

# 01 loading dataset and make tensor
csv_file = pd.read_csv('Real_estate.csv')
csv_file.drop('No', inplace=True, axis=1)
y = csv_file['Y house price of unit area']
x = csv_file.drop('Y house price of unit area', axis=1) 
#print(x.shape, y.shape)
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=3, shuffle=True)
#print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)
X_train = torch.tensor(X_train.values, dtype=torch.float32)
X_test = torch.tensor(X_test.values, dtype=torch.float32)
Y_train = torch.tensor(Y_train.values, dtype=torch.float32).unsqueeze(1)
Y_test = torch.tensor(Y_test.values, dtype=torch.float32).unsqueeze(1)

print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

"""
model = LinearRegression()
model.fit(X_train, Y_train)
y_predict = model.predict(X_test)
print(pd.DataFrame({'Y_test':Y_test, 'Y_predict':y_predict}).head())
"""


# 02 make model
class my_model(nn.Module):
    def __init__(self):
        super().__init__()

        self.my_layer = nn.Sequential(nn.Linear(6, 30),
                                      nn.Sigmoid(),
                                      nn.Linear(30, 100),
                                      nn.Linear(100, 80),
                                      nn.Linear(80, 1),
                                      nn.Sigmoid())
    
    def forward(self, x):
        x = self.my_layer(x)
        return x

model = my_model()

# 03 train my model
epoch = 1000 # how many train count?
LR = 1e-2 # learning rate -> how many update weight?
optimizer = optim.SGD(model.parameters(), lr=LR, momentum=0.9)

for ep in range(epoch):
    y_h = model(X_train) # 01 forward : MPL
    loss_func = func.binary_cross_entropy(y_h, Y_train)
    loss_func_tmp = -(torch.sum(torch.log(y_h**Y_train * (1-y_h)**(1-Y_train)))/331) # 02 loss function
    optimizer.zero_grad() # 누적을 막아줌
    loss_func.backward() # 03 backward : backpropagation
    optimizer.step() # 04 weight update
    # print
    print(f"epoch: {ep}, train_loss: {round(loss_func.item(), 3)}, my_loss: {round(loss_func_tmp.item(), 3)}")



torch.Size([331, 6]) torch.Size([83, 6]) torch.Size([331, 1]) torch.Size([83, 1])
epoch: 0, train_loss: 2.23, my_loss: 2.23
epoch: 1, train_loss: -197.334, my_loss: -inf
epoch: 2, train_loss: -3686.767, my_loss: -inf
epoch: 3, train_loss: -3686.767, my_loss: -inf
epoch: 4, train_loss: -3686.767, my_loss: -inf
epoch: 5, train_loss: -3686.767, my_loss: -inf
epoch: 6, train_loss: -3686.767, my_loss: -inf
epoch: 7, train_loss: -3686.767, my_loss: -inf
epoch: 8, train_loss: -3686.767, my_loss: -inf
epoch: 9, train_loss: -3686.767, my_loss: -inf
epoch: 10, train_loss: -3686.767, my_loss: -inf
epoch: 11, train_loss: -3686.767, my_loss: -inf
epoch: 12, train_loss: -3686.767, my_loss: -inf
epoch: 13, train_loss: -3686.767, my_loss: -inf
epoch: 14, train_loss: -3686.767, my_loss: -inf
epoch: 15, train_loss: -3686.767, my_loss: -inf
epoch: 16, train_loss: -3686.767, my_loss: -inf
epoch: 17, train_loss: -3686.767, my_loss: -inf
epoch: 18, train_loss: -3686.767, my_loss: -inf
epoch: 19, train_loss:

In [157]:
x = torch.tensor([1.], requires_grad=True)
for _ in range(3):
    loss = x**2 # 식
    loss.backward() # 미분 +=
    print(x.grad) # 미분결과
    x.grad = None

#2
#2

tensor([2.])
tensor([2.])
tensor([2.])
